src/Entity/Pigistes.php
<?php

namespace App\Entity;

use App\Repository\PigistesRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=PigistesRepository::class)
 */
class Pigistes
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $nom;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $prenom;

    /**
     * @ORM\Column(type="date")
     */
    private $date_de_naissance;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $lieu_de_naissace;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $adresse;

    /**
     * @ORM\Column(type="string", length=5)
     */
    private $code_postal;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $ville;

    /**
     * @ORM\Column(type="string", length=21)
     */
    private $securite_sociale;

    /**
     * @ORM\Column(type="string", length=6)
     */
    private $matricule;

    /**
     * @ORM\Column(type="string", length=6, nullable=true)
     */
    private $carte_de_presse;

    /**
     * @ORM\Column(type="date", nullable=true)
     */
    private $date_carte_presse;

    /**
     * @ORM\Column(type="string", length=3)
     */
    private $code_emploi;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $nationalite;

    /**
     * @ORM\OneToMany(targetEntity=Contrats::class, mappedBy="pigiste")
     */
    private $contrats;

    /**
     * @ORM\Column(type="boolean")
     */
    private $active;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $libelle;


    public function __construct()
    {
        $this->contrats = new ArrayCollection();
        $this->active = true;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->prenom;
    }

    public function setPrenom(string $prenom): self
    {
        $this->prenom = $prenom;

        return $this;
    }

    public function getDateDeNaissance(): ?\DateTimeInterface
    {
        return $this->date_de_naissance;
    }

    public function setDateDeNaissance(\DateTimeInterface $date_de_naissance): self
    {
        $this->date_de_naissance = $date_de_naissance;

        return $this;
    }

    public function getLieuDeNaissace(): ?string
    {
        return $this->lieu_de_naissace;
    }

    public function setLieuDeNaissace(string $lieu_de_naissace): self
    {
        $this->lieu_de_naissace = $lieu_de_naissace;

        return $this;
    }

    public function getAdresse(): ?string
    {
        return $this->adresse;
    }

    public function setAdresse(string $adresse): self
    {
        $this->adresse = $adresse;

        return $this;
    }

    public function getCodePostal(): ?string
    {
        return $this->code_postal;
    }

    public function setCodePostal(string $code_postal): self
    {
        $this->code_postal = $code_postal;

        return $this;
    }

    public function getVille(): ?string
    {
        return $this->ville;
    }

    public function setVille(string $ville): self
    {
        $this->ville = $ville;

        return $this;
    }

    public function getSecuriteSociale(): ?string
    {
        return $this->securite_sociale;
    }

    public function setSecuriteSociale(string $securite_sociale): self
    {
        $this->securite_sociale = $securite_sociale;

        return $this;
    }

    public function getMatricule(): ?int
    {
        return $this->matricule;
    }

    public function setMatricule(int $matricule): self
    {
        $this->matricule = $matricule;

        return $this;
    }

    public function getCarteDePresse(): ?string
    {
        return $this->carte_de_presse;
    }

    public function setCarteDePresse(?string $carte_de_presse): self
    {
        $this->carte_de_presse = $carte_de_presse;

        return $this;
    }

    public function getDateCartePresse(): ?\DateTimeInterface
    {
        return $this->date_carte_presse;
    }

    public function setDateCartePresse(?\DateTimeInterface $date_carte_presse): self
    {
        $this->date_carte_presse = $date_carte_presse;

        return $this;
    }

    public function getCodeEmploi(): ?string
    {
        return $this->code_emploi;
    }

    public function setCodeEmploi(string $code_emploi): self
    {
        $this->code_emploi = $code_emploi;

        return $this;
    }

    public function getNationalite(): ?string
    {
        return $this->nationalite;
    }

    public function setNationalite(string $nationalite): self
    {
        $this->nationalite = $nationalite;

        return $this;
    }

    /**
     * @return Collection|Contrats[]
     */
    public function getContrats(): Collection
    {
        return $this->contrats;
    }

    public function addContrat(Contrats $contrat): self
    {
        if (!$this->contrats->contains($contrat)) {
            $this->contrats[] = $contrat;
            $contrat->setPigiste($this);
        }

        return $this;
    }

    public function removeContrat(Contrats $contrat): self
    {
        if ($this->contrats->removeElement($contrat)) {
            // set the owning side to null (unless already changed)
            if ($contrat->getPigiste() === $this) {
                $contrat->setPigiste(null);
            }
        }

        return $this;
    }

    public function getActive(): ?bool
    {
        return $this->active;
    }

    public function setActive(bool $active): self
    {
        $this->active = $active;

        return $this;
    }

    public function getLibelle(): ?string
    {
        return $this->libelle;
    }

    public function setLibelle(string $libelle): self
    {
        $this->libelle = $libelle;

        return $this;
    }
}

src/Form/PigistesType.php
<?php

namespace App\Form;

use App\Entity\Pigistes;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\BirthdayType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\IntegerType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class PigistesType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('nom', TextType::class, [
                'label' => 'Nom :',
                'required' => true
            ])
            ->add('prenom', TextType::class, [
                'label' => 'Prénom :',
                'required' => true
            ])
            ->add('date_de_naissance', BirthdayType::class, [
                'label' => 'Date de naissance :',
                'required' => true,
                'widget' => 'single_text'
            ])
            ->add('lieu_de_naissace', TextType::class, [
                'label' => 'Lieu de naissance :',
                'required' => true
            ])
            ->add('adresse', TextType::class, [
                'label' => 'Adresse :',
                'required' => true
            ])
            ->add('code_postal', TextType::class, [
                'label' => 'Code postal :',
                'required' => true
            ])
            ->add('ville', TextType::class, [
                'label' => 'Ville :',
                'required' => true
            ])
            ->add('securite_sociale', TextType::class, [
                'label' => "Numéro S.S. :",
                'required' => true
            ])
            ->add('matricule', TextType::class, [
                'label' => "Numéro de matricule RF :",
                'required' => true
            ])
            ->add('carte_de_presse', TextType::class, [
                'label' => 'Numéro de carte de presse :',
                'required' => false,
                'help' => "Laisser libre si le pigiste n'a pas encore de carte de presse."
            ])
            ->add('date_carte_presse', DateType::class, [
                'label' => "Date d'obtention de la carte de presse :",
                'required' => false,
                'widget' => 'single_text',
                'help' => "Laisser libre si le pigiste n'a pas encore de carte de presse."
            ])
            ->add('code_emploi', TextType::class, [
                'label' => 'Code emploi :',
                'required' => true
            ])
            ->add('nationalite', TextType::class, [
                'label' => 'Nationalité :',
                'required' => true
            ])
            ->add('libelle', TextType::class, [
                'label' => 'Libellé emploi :',
                'required' => true
            ])
            ->add('submit', SubmitType::class, [
                'label' => 'Enregistrer'
            ]);
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Pigistes::class,
        ]);
    }
}

src/Controller/PigistesController.php
<?php

namespace App\Controller;

use App\Entity\Pigistes;
use App\Form\PigistesType;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/pigistes", name="pigistes_")
 */
class PigistesController extends AbstractController
{
    /**
     * @Route("/", name="index")
     */
    public function index(): Response
    {
        $this->denyAccessUnlessGranted('ROLE_USER');
        $pigistes = $this->getDoctrine()
            ->getRepository(Pigistes::class)
            ->findBy([
                'active' => true
            ], [
                'nom' => 'ASC'
            ]);
        return $this->render('pigistes/index.html.twig', [
            'pigistes' => $pigistes,
            'active_menu' => 'pigistes'
        ]);
    }

    /**
     * @Route("/add", name="add")
     */
    public function add(Request $request): Response
    {
        $this->denyAccessUnlessGranted('ROLE_USER');
        $pigiste = new Pigistes();

        $form = $this->createForm(PigistesType::class, $pigiste);

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $pigiste = $form->getData();
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($pigiste);
            $entityManager->flush();
            $this->addFlash('info', 'Le pigiste ' . $pigiste->getNom() . ' a bien été enregistré.');
            return $this->redirectToRoute('pigistes_index');
        }

        return $this->render('pigistes/add.html.twig', [
            'form' => $form->createView(),
            'active_menu' => 'pigistes'
        ]);
    }

    /**
     * @Route("/deactivate/{id}", name="deactivate")
     */
    public function deactivate(Pigistes $pigiste) {
        $this->denyAccessUnlessGranted('ROLE_USER');
        $pigiste->setActive(false);
        $this->getDoctrine()->getManager()->persist($pigiste);
        $this->getDoctrine()->getManager()->flush();

        return $this->redirectToRoute("pigistes_index");
    }

    /**
     * @Route("/edit/{id}", name="edit")
     */
    public function edit(Pigistes $pigiste, Request $request) {
        $this->denyAccessUnlessGranted('ROLE_USER');
        $form = $this->createForm(PigistesType::class, $pigiste);

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $pigiste = $form->getData();
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($pigiste);
            $entityManager->flush();
            $this->addFlash('info', 'Le pigiste ' . $pigiste->getNom() . ' a bien été enregistré.');
            return $this->redirectToRoute('pigistes_index');
        }

        return $this->render('pigistes/edit.html.twig', [
            'form' => $form->createView(),
            'active_menu' => 'pigistes',
            'pigiste' => $pigiste
        ]);
    }
}

templates/pigistes/add.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ parent() }} - ajouter un pigiste{% endblock %}

{% block stylesheets %}
    {{ parent() }}
    <link rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/css/bootstrap-datepicker3.min.css"
          integrity="sha512-rxThY3LYIfYsVCWPCW9dB0k+e3RZB39f23ylUYTEuZMDrN/vRqLdaCBo/FbvVT6uC2r0ObfPzotsfKF9Qc5W5g=="
          crossorigin="anonymous"/>
{% endblock %}

{% block javascripts %}
    {{ parent() }}
    <script src="https://code.jquery.com/jquery-1.12.4.min.js"
            integrity="sha256-ZosEbRLbNQzLpnKIkEdrPv7lOy9C27hHQ+Xp8a4MxAQ=" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/js/bootstrap-datepicker.min.js"
            integrity="sha512-T/tUfKSV1bihCnd+MxKD0Hm1uBBroVYBOYSk1knyvQ9VyZJpc/ALb4P0r6ubwVPSGB2GvjeoMAJJImBG12TiaQ=="
            crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/locales/bootstrap-datepicker.fr.min.js"
            integrity="sha512-fx3aztaUjb4NyoD+Tso5g7R1l29bU3jnnTfNRKBiY9fdQOHzVhKJ10wEAgQ1zM/WXCzB9bnVryHD1M40775Tsw=="
            crossorigin="anonymous"></script>
{% endblock %}

{% block page_content %}
    <div class="row">
        <div class="col-12">
            <div class="bg-dark text-white rounded-lg p-5 mt-2 mb-2">
                <div class="d-flex align-items-center justify-content-between">
                    <div class="col-10">
                        <h1 class="display-4 mb-0 pb-0">Ajouter un pigiste<br/></h1>
                    </div>
                </div>
            </div>
        </div>
    </div>
    {{ form_start(form) }}
    <div class="row">
        <div class="col-6">
            <p class="mt-1">
                {{ form_row(form.nom) }}
            </p>
            <p class="mt-1">
                {{ form_row(form.prenom) }}
            </p>
            <p class="mt-1">
                {{ form_row(form.date_de_naissance, { 'attr' : { 'class' : 'datepickern'}}) }}
            </p>
            <p class="mt-1">
                {{ form_row(form.lieu_de_naissace) }}
            </p>
        </div>
        <div class="col-6">
            <p class="mt-1">
                {{ form_row(form.adresse) }}
            </p>
            <p class="mt-1">
                {{ form_row(form.code_postal) }}
            </p>
            <p class="mt-1">
                {{ form_row(form.ville) }}
            </p>
            <p class="mt-1">
                {{ form_row(form.nationalite) }}
            </p>
        </div>
    </div>
    <div class="row">
        <div class="col-6">
            <p class="mt-1">
                {{ form_row(form.securite_sociale) }}
            </p>
            <p class="mt-1">
                {{ form_row(form.code_emploi) }}
            </p>
        </div>
        <div class="col-6">
            <p class="mt-1">
                {{ form_row(form.matricule) }}
            </p>
            <p class="mt-1">
                {{ form_row(form.libelle) }}
            </p>
        </div>
    </div>
    <div class="row border-light alert alert-info">
        <div class="col-6">
            <p class="mt-1">
                {{ form_row(form.carte_de_presse) }}
            </p>
        </div>
        <div class="col-6">
            <p class="mt-1">
                {{ form_row(form.date_carte_presse, { 'attr' : { 'class' : 'datepicker'}}) }}
            </p>
        </div>
    </div>
    {{ form_end(form) }}
    <script>
        $('.datepickern').datepicker({
            format: "yyyy-mm-dd",
            language: "fr",
            startView: 3,
            orientation: "bottom"
        });
        $('.datepicker').datepicker({
            format: "yyyy-mm-dd",
            language: "fr"
        });
    </script>
{% endblock %}

templates/pigistes/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ parent() }} - modifier {{ pigiste.prenom }} {{ pigiste.nom }}{% endblock %}

{% block page_content %}
    <div class="row">
        <div class="col-6 offset-3">
            <h1>Modifier un pigiste</h1>
            <p>
                {{ form(form) }}
            </p>
        </div>
    </div>
{% endblock %}

templates/pigistes/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ parent() }} - pigistes{% endblock %}

    {% block page_content %}
        <div class="row">
            <div class="col-12">
                <div class="bg-dark text-white rounded-lg p-5 mt-2 mb-2">
                    <div class="d-flex align-items-center justify-content-between">
                        <div class="col-9">
                            <h1 class="display-4">Gestion des pigistes</h1>
                        </div>
                        <div class="col-3">
                            <a href="{{ path('pigistes_add') }}" class="btn btn-outline-info float-end">
                                <i class="fas fa-plus">
                                </i>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        {% if pigistes == null %}
            <div class="alert alert-info">Aucun pigiste enregistré</div>
        {% endif %}
        <div class="row">
            <div class="col-11 offset-1">
                <div class="accordion" id="accordion">
                    {% for pigiste in pigistes %}
                        <div class="accordion-item">
                            <h2 class="accordion-header" id="heading{{ pigiste.id }}">
                                <button class="accordion-button collapsed"
                                        type="button" data-bs-toggle="collapse"
                                        data-bs-target="#collapse{{ pigiste.id }}" aria-expanded="true"
                                        aria-controls="collapse{{ pigiste.id }}">
                                    <strong>{{ pigiste.nom }}</strong>&nbsp;{{ pigiste.prenom }}
                                    &nbsp;<small>({{ pigiste.matricule }})</small>
                                </button>
                            </h2>
                            <div id="collapse{{ pigiste.id }}"
                                 class="accordion-collapse collapse"
                                 aria-labelledby="heading{{ pigiste.id }}" data-bs-parent="#accordionExample">
                                <div class="accordion-body">
                                    <div class="row align-items-center justify-content-between">
                                        <div class="col order-first">
                                            <a href="{{ path('pigistes_edit', { id : pigiste.id }) }}"
                                               class="btn btn-sm btn-outline-info">modifier</a>
                                            <a href="{{ path('pigistes_deactivate', { id : pigiste.id }) }}"
                                               class="btn btn-sm btn-outline-info">desactiver</a>
                                        </div>
                                        <div class="col">
                                            {{ pigiste.adresse }}<br/>
                                            {{ pigiste.codePostal }}&nbsp;{{ pigiste.ville }}
                                        </div>
                                        <div class="col">
                                            Né le {{ pigiste.dateDeNaissance|format_date('long', locale='fr') }}
                                            à {{ pigiste.lieuDeNaissace }}<br/>
                                            Numéro SS : {{ pigiste.SecuriteSociale }}
                                        </div>
                                        <div class="col bg-light border border-1 border-dark">
                                            {% if pigiste.carteDePresse != null %}
                                                Carte de presse n°{{ pigiste.carteDePresse }}<br/>
                                                Date d'obtention : {{ pigiste.DateCartePresse|date("d M y") }}
                                            {% else %}
                                                Non carté
                                            {% endif %}
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    {% endblock %}