src/Entity/Contrats.php
<?php

namespace App\Entity;

use App\Repository\ContratsRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=ContratsRepository::class)
 */
class Contrats
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=8)
     */
    private $numero;

    /**
     * @ORM\Column(type="date")
     */
    private $date_debut;

    /**
     * @ORM\Column(type="date")
     */
    private $date_fin;

    /**
     * @ORM\Column(type="string", length=10)
     */
    private $centre_de_cout;

    /**
     * @ORM\ManyToOne(targetEntity=Pigistes::class, inversedBy="contrats")
     * @ORM\JoinColumn(nullable=false)
     */
    private $pigiste;

    /**
     * @ORM\ManyToOne(targetEntity=Tarifs::class)
     * @ORM\JoinColumn(nullable=false)
     */
    private $tarif;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Motif;

    /**
     * @ORM\Column(type="boolean")
     */
    private $active;

    public function __construct($numero)
    {
        $this->setNumero($numero);
        $this->setActive(true);
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNumero(): ?string
    {
        return $this->numero;
    }

    public function setNumero(string $numero): self
    {
        $this->numero = $numero;

        return $this;
    }

    public function getDateDebut(): ?\DateTimeInterface
    {
        return $this->date_debut;
    }

    public function setDateDebut(\DateTimeInterface $date_debut): self
    {
        $this->date_debut = $date_debut;

        return $this;
    }

    public function getDateFin(): ?\DateTimeInterface
    {
        return $this->date_fin;
    }

    public function setDateFin(\DateTimeInterface $date_fin): self
    {
        $this->date_fin = $date_fin;

        return $this;
    }

    public function getCentreDeCout(): ?string
    {
        return $this->centre_de_cout;
    }

    public function setCentreDeCout(string $centre_de_cout): self
    {
        $this->centre_de_cout = $centre_de_cout;

        return $this;
    }

    public function getPigiste(): ?Pigistes
    {
        return $this->pigiste;
    }

    public function setPigiste(?Pigistes $pigiste): self
    {
        $this->pigiste = $pigiste;

        return $this;
    }

    public function getTarif(): ?Tarifs
    {
        return $this->tarif;
    }

    public function setTarif(?Tarifs $tarif): self
    {
        $this->tarif = $tarif;

        return $this;
    }

    public function getNbJours()
    {
        $date1 = $this->getDateDebut();
        $date2 = $this->getDateFin();
        $interval = $date1->diff($date2);
        return $interval->d + 1;
    }

    public function getMotif(): ?string
    {
        return $this->Motif;
    }

    public function setMotif(string $Motif): self
    {
        $this->Motif = $Motif;

        return $this;
    }

    public function getActive(): ?bool
    {
        return $this->active;
    }

    public function setActive(bool $active): self
    {
        $this->active = $active;

        return $this;
    }
}

src/Form/ContratsType.php
<?php

namespace App\Form;

use App\Entity\Contrats;
use App\Entity\Pigistes;
use App\Entity\Tarifs;
use Doctrine\ORM\EntityRepository;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ContratsType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('date_debut', DateType::class, [
                'label' => "Date de début :",
                'required' => true,
                'widget' => 'single_text'
            ])
            ->add('date_fin', DateType::class, [
                'label' => "Date de fin :",
                'required' => true,
                'widget' => 'single_text'])
            ->add('centre_de_cout', TextType::class, [
                'label' => 'Centre de coût :',
                'required' => true
            ])
            ->add('motif', TextType::class, [
                'label' => 'Motif :',
                'required' => true
            ])
            ->add('pigiste', EntityType::class, [
                'class' => Pigistes::class,
                'query_builder' => function (EntityRepository $er) {
                    return $er->createQueryBuilder('p')
                        ->andWhere('p.active = 1')
                        ->orderBy('p.nom', 'ASC');
                },
                'choice_label' => function ($pigiste) {
                    return $pigiste->getPrenom() . " " . $pigiste->getNom();
                },
                'multiple' => false,
                'expanded' => false,
                'placeholder' => "Choisir un pigiste"
            ])
            ->add('tarif', EntityType::class, [
                'class' => Tarifs::class,
                'query_builder' => function (EntityRepository $er) {
                    return $er->createQueryBuilder('t')
                        ->orderBy('t.id', 'ASC');
                },
                'choice_label' => 'name',
                'multiple' => false,
                'expanded' => false,
                'placeholder' => "Choisir un tarif"
            ])
            ->ad('submit', SubmitType::class, [
                'label' => 'Générer'
            ]);
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Contrats::class,
        ]);
    }
}

src/Controller/ContratsController.php
<?php

namespace App\Controller;

use App\Entity\Contrats;
use App\Form\ContratsType;
use Knp\Component\Pager\PaginatorInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/contrats", name="contrats_")
 */
class ContratsController extends AbstractController
{
    /**
     * @Route("/list/{year}/{month}", name="index")
     */
    public function index($year = null, $month = null, Request $request, PaginatorInterface $paginator): Response
    {
        $this->denyAccessUnlessGranted('ROLE_USER');
        if (!(bool)$year && !(bool)$month) {
            $year = date('Y');
            $month = date('m');
        }
        $date = new \DateTime("$year-$month-01T00:00:00");
        $data = $this->getDoctrine()->getRepository(Contrats::class)->getContractByMonth($year, $month);
        $contrats = $paginator->paginate($data, $request->query->getInt('page', 1), 10);
        $firstContract = $this->getDoctrine()->getRepository(Contrats::class)
            ->findFirstContract();
        $lastContract = $this->getDoctrine()->getRepository(Contrats::class)
            ->findLastContract();
        if (!isset($firstContract)) {
            $dateFirstContract = $date->format('m/Y');
        } else {
            $dateFirstContract = $firstContract->getDateDebut()->format('m/Y');
        }
        if (!isset($lastContract)) {
            $dateLastContract = $date->format('m/Y');
        } else {
            $dateLastContract = $lastContract->getDateDebut()->format('m/Y');
        }
        if ($dateFirstContract == $date->format('m/Y')) {
            $beforeMonth = false;
        } else {
            $beforeMonth = true;
        }
        if ($dateLastContract == $date->format('m/Y')) {
            $afterMonth = false;
        } else {
            $afterMonth = true;
        }
        return $this->render('contrats/index.html.twig', [
            'active_menu' => 'contrats',
            'contrats' => $contrats,
            'date' => $date,
            'month' => $month,
            'year' => $year,
            'after_month' => $afterMonth,
            'before_month' => $beforeMonth
        ]);
    }

    /**
     * @Route("/add", name="add")
     */
    public function add(Request $request)
    {
        $this->denyAccessUnlessGranted('ROLE_USER');
        if ($this->getDoctrine()->getRepository(Contrats::class)->getContractByYear(date('Y')) > 0) {
            $contractNumber = $this->getDoctrine()->getRepository(Contrats::class)->findLastContract()->getNumero();
            $contractNumber += 1;
        } else {
            $number = sprintf('%04d', 1);
            $contractNumber = date('Y') . $number;
        }
        $contrat = new Contrats($contractNumber);
        $form = $this->createForm(ContratsType::class, $contrat);
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            $contrat = $form->getData();
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($contrat);
            $entityManager->flush();
            $this->addFlash('info', 'Le contrat n°' . $contrat->getNumero() . ' a bien été enregistré.');
            return $this->redirect($request->headers->get('referer'));
        }
        return $this->render('contrats/add.html.twig', [
            'form' => $form->createView(),
            'active_menu' => 'contrats'
        ]);
    }

    /**
     * @Route("/edit/{id}", name="edit")
     */
    public function edit(Contrats $contrat, Request $request)
    {
        $this->denyAccessUnlessGranted('ROLE_USER');
        $form = $this->createForm(ContratsType::class, $contrat);
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            $contrat = $form->getData();
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($contrat);
            $entityManager->flush();
            $this->addFlash('info', 'Le contrat n°' . $contrat->getNumero() . ' a bien été modifié.');
            return $this->redirectToRoute('contrats_index');
            return $this->redirect($request->headers->get('referer'));
        }
        return $this->render('contrats/edit.html.twig', [
            'form' => $form->createView(),
            'active_menu' => 'contrats'
        ]);
    }

    /**
     * @Route("/disable/{id}", name="disable")
     */
    public function disable(Contrats $contrats, Request $request)
    {
        $this->denyAccessUnlessGranted('ROLE_USER');
        $contrats->setActive(false);
        $this->getDoctrine()->getManager()->persist($contrats);
        $this->getDoctrine()->getManager()->flush();
        return $this->redirect($request->headers->get('referer'));
    }

    /**
     * @Route("/enable/{id}", name="enable")
     */
    public function enable(Contrats $contrats, Request $request)
    {
        $this->denyAccessUnlessGranted('ROLE_USER');
        $contrats->setActive(true);
        $this->getDoctrine()->getManager()->persist($contrats);
        $this->getDoctrine()->getManager()->flush();
        return $this->redirect($request->headers->get('referer'));
    }

    /**
     * @Route("/print/{id}", name="print")
     */
    public function print(Contrats $contrats)
    {
        $this->denyAccessUnlessGranted('ROLE_USER');
        $pdf = new \TCPDF('P', 'mm', 'A4', true, 'UTF-8', false);

// set document information
        $pdf->SetCreator('Radio France');
        $pdf->SetAuthor('Radio France');
        $pdf->SetTitle('Contrat n°' . $contrats->getNumero());
        $pdf->SetPrintHeader(false);
        $pdf->SetPrintFooter(false);

// set default monospaced font
        $pdf->SetDefaultMonospacedFont(PDF_FONT_MONOSPACED);

// set margins
        $pdf->SetMargins(2, 5, 2);

// set auto page breaks
        $pdf->SetAutoPageBreak(TRUE, 0);

// set image scale factor
        $pdf->setImageScale(PDF_IMAGE_SCALE_RATIO);

// ---------------------------------------------------------

// set default font subsetting mode
        $pdf->setFontSubsetting(true);

// Set font
// dejavusans is a UTF-8 Unicode font, if you only need to
// print standard ASCII chars, you can use core fonts like
// helvetica or times to reduce file size.
        // set cell padding
        $pdf->setCellPaddings(1, 1, 1, 1);

// set cell margins
        $pdf->setCellMargins(1, 0, 1, 0);

// Add a page
// This method has several options, check the source code documentation for more information.
        $pdf->AddPage();

        $txt = "CONTRAT DE TRAVAIL " . $contrats->getNumero();
        $pdf->SetFont('times', 'B', 12, '', true);
        $pdf->MultiCell(0, 0, $txt, 1, "C", false, 1, 28, 3);
        $pdf->Image("img/logo.jpg", 3, 3, 25, 25, '', '', '', true);
        $pdf->ln(15);
        $y = $pdf->getY();
        $pdf->setFont('times', '', 12);
        $pdf->MultiCell(103, 8, 'EMPLOYEUR', 1, "C", false, 0, 0, $y + 3, $valign = "M");
        $pdf->MultiCell(103, 8, 'SALARIE', 1, "C", false, 1, 103, $y + 3, $valign = "M");
        $pdf->setFont('times', '', 11);
        $html = "
<table style='border:none'>
<tr>
<td><strong>Matricule Radio France :</strong></td>
<td>" . $contrats->getPigiste()->getMatricule() . "</td>
</tr>
<tr>
<td><strong>Nom :</strong></td>
<td>" . strtoupper($contrats->getPigiste()->getNom()) . "</td>
</tr>
<tr>
<td><strong>Prénom :</strong></td>
<td>" . $contrats->getPigiste()->getPrenom() . "</td>
</tr>
<tr>
<td><strong>Pseudonyme :</strong></td>
<td></td>
</tr>
<tr>
<td><strong>Adresse :</strong></td>
<td>" . $contrats->getPigiste()->getAdresse() . "<br/>
" . $contrats->getPigiste()->getCodePostal() . " " . $contrats->getPigiste()->getVille() . "
</td>
</tr>
<tr><td></td></tr>
<tr>
<td><strong>N° S.S. :</strong></td>
<td>" . $contrats->getPigiste()->getSecuriteSociale() . "</td>
</tr>
<tr>
<td><strong>Date et lieu de naissance :</strong></td>
</tr>
<tr>
<td>" . $contrats->getPigiste()->getDateDeNaissance()->format('d/m/Y') . "</td>
<td>" . $contrats->getPigiste()->getLieuDeNaissace() . "</td>
</tr>
<tr>
<td></td>
</tr>
<tr>
<td><strong>Nationalité :</strong></td>
<td>" . $contrats->getPigiste()->getNationalite() . "</td>
</tr>
</table>
<table style='border:none'>
<tr>
<td><strong>Titre de séjour :</strong></td>
</tr>
<tr>
<td><strong>N° :</strong></td>
</tr>
</table>
";
        $pdf->WriteHTMLCell(103, 0, 103, $y + 11, $html, 1, 1, false);
        $html = "
<table style='border: none'>
    <tr>
        <td><strong>Dénomination sociale : </strong></td>
        <td>RADIO FRANCE</td>
    </tr>
    <tr>
        <td><strong>Adresse :</strong></td>
        <td>116 Av. du Pdt KENNEDY<br/>
            75220 PARIS CEDEX 16
        </td>
    </tr>
    <tr>
        <td><strong>Code NAF :</strong></td>
        <td>6010Z</td>
    </tr>
    <tr>
        <td colspan='2' align='center'><strong>Service d'affectation :</strong></td>
    </tr>
    <tr>
        <td><strong>Adresse :</strong></td>
        <td>France Bleu Normandie -Rouen-<br/>
        Hangar A, Quai de Boisguilbert<br/>
        76000 ROUEN</td>
    </tr>
</table>
<table style='border:none'>
    <tr>
        <td><strong>N° Siret :</strong> 326094471 01494-01155-01270</td>
    </tr>
    <tr style='border-bottom-style: dashed; border-bottom-width: 1px'>
        <td><strong>URSSAF de la Hte-Garonne : 000020326094471</strong></td>
    </tr>
</table>
<table style='border:none'>
    <tr>
        <td><strong>Direction :</strong></td>
        <td>Délégation Régionale Nord-Normandie</td>
    </tr>
    <tr>
        <td><strong>Service :</strong></td>
        <td>France Bleu Normandie -Rouen-</td>
    </tr>
    <tr>
        <td><strong>Centre de coût :</strong></td>
        <td><em><strong>" . $contrats->getCentreDeCout() . "</strong></em></td>
    </tr>
</table>
";

templates/contrats/add.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ parent() }} - générer un contrat{% endblock %}

{% block stylesheets %}
    {{ parent() }}
    <link rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/css/bootstrap-datepicker3.min.css"
          integrity="sha512-rxThY3LYIfYsVCWPCW9dB0k+e3RZB39f23ylUYTEuZMDrN/vRqLdaCBo/FbvVT6uC2r0ObfPzotsfKF9Qc5W5g=="
          crossorigin="anonymous"/>
{% endblock %}

{% block javascripts %}
    {{ parent() }}
    <script src="https://code.jquery.com/jquery-1.12.4.min.js"
            integrity="sha256-ZosEbRLbNQzLpnKIkEdrPv7lOy9C27hHQ+Xp8a4MxAQ=" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/js/bootstrap-datepicker.min.js"
            integrity="sha512-T/tUfKSV1bihCnd+MxKD0Hm1uBBroVYBOYSk1knyvQ9VyZJpc/ALb4P0r6ubwVPSGB2GvjeoMAJJImBG12TiaQ=="
            crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/locales/bootstrap-datepicker.fr.min.js"
            integrity="sha512-fx3aztaUjb4NyoD+Tso5g7R1l29bU3jnnTfNRKBiY9fdQOHzVhKJ10wEAgQ1zM/WXCzB9bnVryHD1M40775Tsw=="
            crossorigin="anonymous"></script>
{% endblock %}

{% block page_content %}
    <div class="row">
        <div class="col-12">
            <div class="bg-dark text-white rounded-lg p-5 mt-2 mb-2">
                <div class="d-flex align-items-center justify-content-between">
                    <div class="col-10">
                        <h1 class="display-4 mb-0 pb-0">Générer un contrat<br/></h1>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-6">
            {{ form_start(form) }}
            <p class="mt-1">
                {{ form_row(form.pigiste) }}
            </p>
            <p class="mt-1">
                {{ form_row(form.tarif) }}
            </p>
            <p class="mt-1">
                {{ form_row(form.centre_de_cout) }}
            </p>
        </div>
        <div class="col-6">
            <p class="mt-1">
                {{ form_row(form.date_debut, { 'attr' : { 'class' : 'datepicker'}}) }}
            </p>
            <p class="mt-1">
                {{ form_row(form.date_fin, {'attr' : {'class' : 'datepicker'}}) }}
            </p>
            <p class="mt-1">
                {{ form_row(form.motif) }}
            </p>
            <p class="mt-1 text-right">
                {{ form_row(form.submit) }}
            </p>
            {{ form_end(form) }}
        </div>
    </div>
    <script>
        $('.datepicker').datepicker({
            format: "yyyy-mm-dd",
            language: "fr",
            orientation: "bottom"
        });
    </script>
{% endblock %}

templates/contrats/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ parent() }} - générer un contrat{% endblock %}

{% block page_content %}
    <div class="row">
        <div class="col-12">
            <div class="bg-dark text-white rounded-lg p-5 mt-2 mb-2">
                <div class="d-flex align-items-center justify-content-between">
                    <div class="col-10">
                        <h1 class="display-4 mb-0 pb-0">Modifier un contrat<br/></h1>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-6 offset-3">
            <p>
                {{ form(form) }}
            </p>
        </div>
    </div>
{% endblock %}

templates/contrats/index.html.twig
{% extends 'base.html.twig' %}

{% block page_content %}
    <div class="row">
        <div class="col-12">
            <div class="bg-dark text-white rounded-lg p-5 mt-2 mb-2">
                <div class="d-flex align-items-center justify-content-between">
                    <div class="col-9">
                        <h1 class="display-4 mb-0">Gestion des contrats</h1>
                        <p class="mt-0 text-info">{{ date|format_date(date_format='medium', locale='fr', pattern='MM/Y') }}</p>
                    </div>
                    <div class="col-3">
                        <a href="{{ path('contrats_add') }}" class="btn btn-outline-info float-end">
                            <i class="fas fa-plus">
                            </i>
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-12 d-flex justify-content-between align-items-center">
            <nav aria-label="Month navigation">
                <ul class="pagination justify-content-center">
                    {% if before_month == true %}
                        {% if month == 1 %}
                            <li class="page-item"><a class="page-link"
                                                     href="{{ path('contrats_index', { 'month' : 12, 'year' : year - 1}) }}">Mois
                                    précédent</a></li>
                        {% else %}
                            <li class="page-item"><a class="page-link"
                                                     href="{{ path('contrats_index', { 'month' : month - 1, 'year' : year }) }}">Mois
                                    précédent</a></li>
                        {% endif %}
                    {% endif %}
                    {% if after_month == true %}
                        {% if month == 12 %}
                            <li class="page-item"><a class="page-link"
                                                     href="{{ path('contrats_index', { 'month' : 1, 'year' : year + 1}) }}">Mois
                                    suivant</a></li>
                        {% else %}
                            <li class="page-item"><a class="page-link"
                                                     href="{{ path('contrats_index', { 'month' : month + 1, 'year' : year }) }}">Mois
                                    suivant</a></li>
                        {% endif %}
                    {% endif %}
                </ul>
            </nav>
            <div>
                {{ knp_pagination_render(contrats) }}
            </div>
        </div>
    </div>
    <div class="row mb-5">
        <div class="col-11 offset-1">
            <ul class="list-group">
                {% for contrat in contrats %}
                    <li class="list-group-item d-flex justify-content-between">
                        {% if contrat.active == true %}
                        <div>
                            <a class="fas fa-edit text-info text-decoration-none"
                               href="{{ path('contrats_edit', { 'id' : contrat.id}) }}"></a>
                            <a class="fas fa-print text-info text-decoration-none"
                               href="{{ path('contrats_print', { 'id' : contrat.id }) }}"></a>
                        </div>
                        {% else %}
                            <div>
                                <i class="fas fa-ban"></i>
                            </div>
                            {% endif %}
                        <div class="text-center{% if contrat.active != true %} text-danger{% endif %}">{{ contrat.pigiste.prenom }} {{ contrat.pigiste.nom }}</div>
                        <div class="text-center{% if contrat.active != true %} text-danger{% endif %}">{{ contrat.dateDebut|date('d/m/Y') }}
                            - {{ contrat.dateFin|date('d/m/Y') }}</div>
                        <div>{% if contrat.active == true %}
                                <a class="far fa-trash-alt text-info text-decoration-none"
                                   href="{{ path('contrats_disable', { 'id' : contrat.id }) }}"></a>
                            {% else %}
                                <a class="far fa-redo-alt text-info text-decoration-none"
                                   href="{{ path('contrats_enable', { 'id' : contrat.id }) }}"></a>
                            {% endif %}
                        </div>
                    </li>
                {% endfor %}
            </ul>
        </div>
    </div>
{% endblock %}